### ISSUE TITLE
Video Call - Remote Participant Mirror Display

### ISSUE THREAD

**Issue by HakanSAYAR** [twilio/twilio-video-app-ios#104]
#### Description

Hi, I'm developing a P2P&Group video call application using your SDK. If the front camera of the remote participant is open, it display a mirror image, there is no problem when the back camera is open. How can I solve this?

#### Versions

- Video app version: 3.5
- iOS version:  13.5.1
- Device: iPhone 7
- Xcode version: 11.6

**Comment by timrozum** [comment]
Hi @HakanSAYAR,

It sounds like you don't want to mirror the front or back camera. You can achieve this by changing [this line](https://github.com/twilio/twilio-video-app-ios/blob/1f12902515a4fa12c88ee985554cf3064f729074/VideoApp/VideoApp/Video/Participants/LocalParticipant.swift#L26) to always return `false`. Please let me know if this helps.

FYI for our demo application we choose to mirror the front camera so that the user sees a reflection when viewing local video of themself so this is by design.

**Comment by timrozum** [comment]
Actually I just read the title of this issue again and realize this refers to remote participants. I will do some testing and get back to you. Thanks!

**Comment by timrozum** [comment]
@HakanSAYAR I have verified that the app does not mirror remote participant video for any camera so I'm not sure what problem you are seeing.

Perhaps the UI is causing confusion. The first participant in the participant list is the local participant (so they can preview their own video) and the video is mirrored locally when using the front camera. All other participants after the local participant are remote participants and the video should not be mirrored. 

If this does not help with the issue could you provide more detail such as exactly how you are testing and maybe screenshots?

Thanks!

**Comment by HakanSAYAR** [comment]
@timrozum I tested it again. The UI does not cause confusion, so there is no problem with this. When I set [this line](https://github.com/twilio/twilio-video-app-ios/blob/1f12902515a4fa12c88ee985554cf3064f729074/VideoApp/VideoApp/Video/Participants/RemoteParticipant.swift#L21)  to `true`, there is no problem with the image on the front camera of the remote participant, but it display the mirror image of the image on the back camera. When I set `false` it works just the opposite. Maybe this detail can help you? Actually, it works like this in your demo application.

**Test Case**
**Actually Result**
1. User X and Y are connected to the same room.
2. The front cameras of X and Y users are open.
3. User X turns his head to the left.
4. User X sees himself with his head turned to the left.
**5. User Y sees the head of user X as turned to the right.**

**Expected Result**
1. User X and Y are connected to the same room.
2. The front cameras of X and Y users are open.
3. User X turns his head to the left.
4. User X sees himself with his head turned to the left.
**5. User Y sees the head of user X as turned to the left.**

**Comment by timrozum** [comment]
Hi @HakanSAYAR,

Thanks for confirming. I think I understand you want to mirror the remote participant video for the front camera only. Typically it is only desirable to mirror local video from front camera. However you should be able to achieve your desired result.

Specify a track name when publishing video that allows you to understand on the receiving side if the video is from the front or rear camera. For example instead of `camera` use `front-camera` for the track name. And then you will have enough information to know if the video should be mirrored or not when received. A downside of this is that the entire video track will need to be unpublished and republished each time the user switches camera because track name cannot be modified.

Hope this helps!
