### ISSUE TITLE
Video Call - Pause

### ISSUE THREAD

**Issue by HakanSAYAR** [twilio/twilio-video-app-ios#105]
Description
Hi, I'm developing a P2P&Group video call application using your SDK. When I put the application into the background while I was in a video call, it shows the remote participant a white screen. How can I show my last image? (like whatsapp)

Versions
Video app version: 3.5
iOS version: 13.5.1
Device: iPhone 7
Xcode version: 11.6

**Comment by timrozum** [comment]
Hi @HakanSAYAR,

I believe in this case on iOS we show a black view so I'm not sure what white you are referring to. But I think there are a couple ways to achieve your desired result:

1. I think if you modify [this code](https://github.com/twilio/twilio-video-app-ios/blob/1f12902515a4fa12c88ee985554cf3064f729074/VideoApp/VideoApp/Video/Participants/LocalParticipant.swift#L159-L167) so that the track is never disabled the UI will show the last frame. This solution will only work if you don't have other uses for enabled state in your UI.
1. You could modify [this code](https://github.com/twilio/twilio-video-app-ios/blob/1f12902515a4fa12c88ee985554cf3064f729074/VideoApp/VideoApp/Views/VideoView/VideoView.swift#L46-L69) so that it doesn't hide the video view when there is no data. 

I hope this helps!
