### ISSUE TITLE
Create the Passcode with api

### ISSUE THREAD

**Issue by aaparth** [twilio/twilio-video-app-ios#124]
Hello there,

We are integrating the twillio in our app and as seen from the docs we need to generate the passcode using the twillio CLI and that too expires after the week of time. 

Is there any other way we could generate the passcode using any apis or nodeJS sdk or anything else we could do.

**Comment by timrozum** [comment]
Hi @aaparth,

The passcode implementation is intended to be an easy way to try out the video app quickly and is not intended for production. 

Here is a link with some information and example solutions for implementing your own access token server: https://www.twilio.com/docs/video/tutorials/user-identity-access-tokens#generating-access-tokens

This way you can use whatever auth you want instead of passcode, such as Google sign in, to fetch your access token.

Hopefully that helps!

**Comment by timrozum** [comment]
I'm going to close this issue but feel free to reach out here again if the path forward is not yet clear.

**Comment by aaparth** [comment]
hello @timrozum 

Thanks for the quick reply. I will check and if any issue persist then will get back to you.
