### ISSUE TITLE
Unable to do Pod Install

### ISSUE THREAD

**Issue by tripathishivam35** [twilio/twilio-video-app-ios#157]
![Screenshot 2021-05-04 at 3 48 04 AM](https://user-images.githubusercontent.com/13601158/116940562-c1653880-ac8b-11eb-80b6-0190977ca0e6.png)

I tried updating Ruby to latest 3.0 and installing pods again. However didn't got succeed. Always getting this error wrong number of arguments while doing pod install (ref screenshot attached). Can u help me with it?

**Comment by timrozum** [comment]
Hi @tripathishivam35, could you provide the command you are running? I don't see it in the screenshot. Thanks.

**Comment by tripathishivam35** [comment]
i am using command - "pod install" as suggested in readme file.

**Comment by timrozum** [comment]
Ok I can't think of anything in particular that would cause this issue but here are some ideas:

1. Try using pod version `1.10.0` since that is the version we are using internally.
2. There really isn't much information in the pod error which is surprising. Might have to reach out to CocoaPods about this.

Let me know if changing pod version helps.

**Comment by tripathishivam35** [comment]
Strangely It was not working 2 days back but today pod got installed without any change. 
Anyways I was on version 1.10.1
